# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/KarthikMAM/go-ecs

    steps:
      - checkout

      - run: 
          name: Running Unit Tests
          command: go test

      - run: 
          name: build
          command: go build

  generate_and_upload_build:
    machine: true
    steps:
      - checkout

      - run:
          name: Build and Upload Build to ECR
          command: bash ./scripts/build.sh

workflows:
    version: 2
    
    test-and-deploy:
      jobs:
        - build
        - hold:
            type: approval
            requires:
             - build
        - generate_and_upload_build:
            requires:
             - hold
            filters:
              branches:
                only:
                  - master